#!/usr/bin/env python3
"""Resolve the pinned upstream releases and generate the .inc files recipes need.

Companion to fetch-fpga-ipks.py, and part of the same step 1 of the build.

The recipes built from a GitHub checkout -- panda-server, kernel-module-panda
and python3-panda-webcontrol -- do not carry their `SRCREV` and `PV`.  Those are
pinned as a git tag in a top-level release file, one per upstream repository:

    panda-server-release.txt      -> panda-server, kernel-module-panda
    panda-webcontrol-release.txt  -> python3-panda-webcontrol

This script resolves each tag to a commit and writes it into a generated .inc
that the recipes `require`, so bumping a version is a one-line edit with no sha
to copy by hand.  It also means the two recipes built from one
PandABlocks-server checkout cannot drift apart: there is only one place to
change.  The generated .inc files are gitignored, like the generated FPGA
recipes, and a missing one fails the build at parse time rather than silently.

Resolving uses `git ls-remote`, so this needs the network -- but only when a
tag actually changes: the generated .inc records the tag it came from and a
matching one is reused as is.  `--force` resolves again anyway.
"""

import argparse
import re
import subprocess
import sys
from collections import namedtuple
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent

# release_file and inc are relative to REPO_DIR; recipes is for messages only.
Source = namedtuple("Source", "release_file repo inc recipes")

SOURCES = {
    "panda-server": Source(
        release_file="panda-server-release.txt",
        repo="https://github.com/PandABlocks/PandABlocks-server",
        inc="recipes-panda/panda-server-generated/panda-server-release.inc",
        recipes="panda-server and kernel-module-panda",
    ),
    "panda-webcontrol": Source(
        release_file="panda-webcontrol-release.txt",
        repo="https://github.com/PandABlocks/PandABlocks-webcontrol",
        inc="recipes-panda/panda-webcontrol-generated/panda-webcontrol-release.inc",
        recipes="python3-panda-webcontrol",
    ),
}

# The tag of an already generated .inc, read back out of the PV it wrote.
PV_RE = re.compile(r'^PV = "(?P<tag>.+)\+git\$\{SRCPV\}"$', re.MULTILINE)
SRCREV_RE = re.compile(r'^SRCREV = "(?P<rev>[0-9a-f]{40})"$', re.MULTILINE)


def die(message):
    sys.exit(f"error: {message}")


def read_pinned_release(source):
    path = REPO_DIR / source.release_file
    if not path.exists():
        die(f"{source.release_file} not found; pass --release instead")
    tag = path.read_text().strip()
    if not tag:
        die(f"{source.release_file} is empty")
    if len(tag.split()) > 1:
        die(f"{source.release_file} should hold a single release tag, got {tag!r}")
    return tag


def already_resolved(source, tag):
    """The sha a previous run pinned for this tag, or None to go and look.

    Re-resolving on every build would put the network on the path of a build
    that sstate could otherwise do offline, and a tag does not move.
    """
    path = REPO_DIR / source.inc
    if not path.exists():
        return None
    text = path.read_text()
    pv, srcrev = PV_RE.search(text), SRCREV_RE.search(text)
    if not pv or not srcrev or pv.group("tag") != tag:
        return None
    return srcrev.group("rev")


def resolve_tag(source, tag):
    """The commit `tag` names in the source's repository.

    An annotated tag has both a `refs/tags/<tag>` line for the tag object and a
    peeled `refs/tags/<tag>^{}` line for the commit; it is the commit we want,
    since that is what BitBake checks out.
    """
    ref = f"refs/tags/{tag}"
    print(f"Resolving {ref} in {source.repo}")
    try:
        result = subprocess.run(
            ["git", "ls-remote", source.repo, ref, ref + "^{}"],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        die("git not found; it is needed to resolve the release tags")
    if result.returncode != 0:
        die(f"git ls-remote {source.repo} failed: {result.stderr.strip()}")

    revs = {}
    for line in result.stdout.splitlines():
        rev, _, name = line.partition("\t")
        revs[name] = rev
    if not revs:
        die(
            f"{source.repo} has no tag {tag!r}; check {source.release_file} "
            "(or the --release you passed)"
        )
    return revs.get(ref + "^{}") or revs[ref]


def write_inc(source, tag, rev):
    path = REPO_DIR / source.inc
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"# Generated by {Path(__file__).name} from {source.release_file}.\n"
        f"# Do not edit -- regenerate with ./{Path(__file__).name}\n"
        "#\n"
        f"# The pinned release of {source.repo},\n"
        f"# required by {source.recipes}.\n"
        "\n"
        f'SRCREV = "{rev}"\n'
        f'PV = "{tag}+git${{SRCPV}}"\n'
    )
    print(f"Wrote {source.inc}")


def generate(source, tag, force):
    print(f"{source.repo.rsplit('/', 1)[-1]} release: {tag}")
    rev = None if force else already_resolved(source, tag)
    if rev:
        print(f"{source.inc} already pins {tag} at {rev[:12]}")
        return
    write_inc(source, tag, resolve_tag(source, tag))


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "sources",
        metavar="SOURCE",
        nargs="*",
        help=f"which to generate: {', '.join(SOURCES)} (default: all of them)",
    )
    parser.add_argument(
        "--release",
        metavar="TAG",
        help="release tag to pin, instead of the one in the release file; "
        "needs a single SOURCE, since the tag is per repository",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="resolve the tag again even if the generated .inc already pins it",
    )
    args = parser.parse_args()

    unknown = [name for name in args.sources if name not in SOURCES]
    if unknown:
        parser.error(
            f"unknown SOURCE {', '.join(unknown)}; "
            f"choose from {', '.join(SOURCES)}"
        )
    names = args.sources or list(SOURCES)
    if args.release and len(names) != 1:
        parser.error("--release needs exactly one SOURCE")

    for name in names:
        source = SOURCES[name]
        generate(source, args.release or read_pinned_release(source), args.force)


if __name__ == "__main__":
    main()
