#!/usr/bin/env python3
"""Fetch the prebuilt PandABlocks-FPGA ipks and generate BitBake recipes for them.

This is step 1 of the two-step build; step 2 is the usual `kas build`.

PandABlocks-FPGA publishes every bitstream and boot package for a release as a
single `panda-fpga-ipks.tar.gz` asset.  We download that, unpack it flat into
`ipks/`, and write one recipe per ipk into `recipes-panda/panda-fpga-generated/`.
The ipk filename carries everything BitBake needs -- `<PN>_<PV>_all.ipk` -- so
there is nothing to pin by hand and no sha256 to recompute: a `file://` SRC_URI
is checksummed into the task signature automatically.

The release tag is pinned in `fpga-release.txt`.  To build against a locally
built bitstream instead, drop its ipk into `ipks/` and re-run with
`--no-download`.
"""

import argparse
import re
import shutil
import sys
import tarfile
import urllib.error
import urllib.request
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent
IPK_DIR = REPO_DIR / "ipks"
GENERATED_DIR = REPO_DIR / "recipes-panda" / "panda-fpga-generated"
RELEASE_FILE = REPO_DIR / "fpga-release.txt"
MACHINE_CONF_DIR = REPO_DIR / "conf" / "machine"

# Named by upload-gl-release-to-gh.py, which is what produces this asset.
TARBALL_NAME = "panda-fpga-ipks-{tag}.tar.gz"
TARBALL_URL = (
    "https://github.com/PandABlocks/PandABlocks-FPGA/releases/download/"
    "{tag}/" + TARBALL_NAME
)

# The boot ipks are all `Package: panda-fpga-boot` and encode the machine in the
# version field (`pandabox-5.0b1`), so they become one machine-overridden recipe
# rather than one recipe each.
BOOT_PN = "panda-fpga-boot"
BITSTREAM_PREFIX = "panda-fpga-"

# The slow FPGA firmware rides in the same tarball but is not machine-named, so
# it cannot be placed in the packagegroup by the usual filename rule.  It is
# PandABox-only, which is what panda-load-firmware assumes too: it loads
# slow_top.bin only when /proc/device-tree/model says PandABox.
SLOWFPGA_PN = "panda-slowfpga"
PACKAGE_MACHINES = {SLOWFPGA_PN: "pandabox"}

IPK_RE = re.compile(r"^(?P<pn>[a-z0-9][a-z0-9.+-]*)_(?P<pv>[^_]+)_all\.ipk$")

GENERATED_HEADER = (
    "# Generated by fetch-fpga-ipks.py from {source}.\n"
    "# Do not edit -- regenerate with ./fetch-fpga-ipks.py\n"
)


def warn(message):
    print(f"warning: {message}", file=sys.stderr)


def die(message):
    sys.exit(f"error: {message}")


def read_pinned_release():
    if not RELEASE_FILE.exists():
        die(f"{RELEASE_FILE.name} not found; pass --release instead")
    tag = RELEASE_FILE.read_text().strip()
    if not tag:
        die(f"{RELEASE_FILE.name} is empty")
    return tag


def known_machines():
    return {conf.stem for conf in MACHINE_CONF_DIR.glob("*.conf")}


def download_tarball(tag):
    """Download the release tarball.

    Always re-downloaded rather than cached on the tag: the asset is uploaded
    with `gh release upload --clobber`, so the contents behind a tag do change.
    Use --no-download to work offline.
    """
    tarball = IPK_DIR / TARBALL_NAME.format(tag=tag)
    url = TARBALL_URL.format(tag=tag)
    print(f"Downloading {url}")
    try:
        with urllib.request.urlopen(url) as response:
            payload = response.read()
    except urllib.error.HTTPError as exc:
        die(f"could not download {url}: HTTP {exc.code} {exc.reason}")
    except urllib.error.URLError as exc:
        die(f"could not download {url}: {exc.reason}")

    # Write via a temporary name so an interrupted download never leaves a
    # truncated tarball in place of the previous good one.
    partial = tarball.with_suffix(".part")
    partial.write_bytes(payload)
    partial.rename(tarball)
    return tarball


def extract_tarball(tarball):
    """Unpack the ipks flat into IPK_DIR, replacing any ipks already there."""
    for stale in IPK_DIR.glob("*.ipk"):
        stale.unlink()

    with tarfile.open(tarball) as tar:
        members = []
        for member in tar.getmembers():
            if not member.isfile():
                continue
            # The tarball is flat by contract; refuse anything that would
            # escape IPK_DIR rather than trusting it.
            if "/" in member.name or member.name in (".", ".."):
                die(f"unexpected path {member.name!r} in {tarball.name}")
            if not member.name.endswith(".ipk"):
                warn(f"skipping non-ipk member {member.name}")
                continue
            members.append(member)
        if not members:
            die(f"no ipks found in {tarball.name}")
        tar.extractall(IPK_DIR, members=members)

    print(f"Extracted {len(members)} ipks into {IPK_DIR.relative_to(REPO_DIR)}")


def collect_ipks():
    """Sort the ipks in IPK_DIR into boot packages and everything else."""
    packages = []           # (pn, pv, filename)
    boots = {}                # machine -> filename
    boot_versions = set()

    for path in sorted(IPK_DIR.glob("*.ipk")):
        match = IPK_RE.match(path.name)
        if not match:
            warn(f"skipping {path.name}: not a <name>_<version>_all.ipk")
            continue
        pn, pv = match.group("pn"), match.group("pv")

        if pn == BOOT_PN:
            machine, _, version = pv.partition("-")
            if not version:
                die(f"{path.name}: boot ipk version {pv!r} has no <machine>- prefix")
            if machine in boots:
                die(f"two boot ipks for machine {machine}: {boots[machine]}, {path.name}")
            boots[machine] = path.name
            boot_versions.add(version)
        else:
            packages.append((pn, pv, path.name))

    if len(boot_versions) > 1:
        die(
            "boot ipks disagree on version ("
            + ", ".join(sorted(boot_versions))
            + "); they share one recipe and so must share one version"
        )

    return packages, boots, boot_versions.pop() if boot_versions else None


def machine_of(pn):
    """The machine a package belongs to, or None if undeterminable.

    `panda-fpga-pandabox2-fmc-acq430` -> `pandabox2`, `panda-fpga-pandabrick` ->
    `pandabrick`.  Matching the first token exactly (rather than by prefix)
    is what keeps `pandabox2` from being read as `pandabox`.
    """
    if pn in PACKAGE_MACHINES:
        return PACKAGE_MACHINES[pn]
    if not pn.startswith(BITSTREAM_PREFIX):
        return None
    return pn[len(BITSTREAM_PREFIX):].split("-")[0]


def write_package_recipes(packages):
    for pn, pv, filename in packages:
        recipe = GENERATED_DIR / f"{pn}_{pv}.bb"
        recipe.write_text(
            GENERATED_HEADER.format(source=filename)
            + "\n"
            + "require recipes-panda/panda-fpga/panda-fpga.inc\n"
            + '\nFILESEXTRAPATHS:prepend := "${THISDIR}/../../ipks:"\n'
            + f'SRC_URI = "file://{filename}"\n'
        )
        print(f"Wrote {recipe.relative_to(REPO_DIR)}")


def write_boot_recipe(boots, version):
    sources = ", ".join(boots[machine] for machine in sorted(boots))
    lines = [
        GENERATED_HEADER.format(source=sources),
        "\n",
        "require recipes-panda/panda-fpga/panda-fpga-boot.inc\n",
        "\n",
        'FILESEXTRAPATHS:prepend := "${THISDIR}/../../ipks:"\n',
    ]
    for machine in sorted(boots):
        lines.append(f'SRC_URI:{machine} = "file://{boots[machine]}"\n')

    recipe = GENERATED_DIR / f"{BOOT_PN}_{version}.bb"
    recipe.write_text("".join(lines))
    print(f"Wrote {recipe.relative_to(REPO_DIR)}")


def write_packagegroup(packages):
    """Per-machine RDEPENDS for packagegroup-panda-fpga, derived from the ipks.

    Always written, even when empty: packagegroup-panda-fpga.bb `require`s this
    file, and a successful run must always leave it in a parseable state.
    """
    machines = known_machines()
    by_machine = {}
    for pn, _pv, filename in packages:
        machine = machine_of(pn)
        if machine is None or machine not in machines:
            warn(
                f"{filename}: no conf/machine/{machine}.conf, leaving {pn} out "
                "of packagegroup-panda-fpga"
            )
            continue
        by_machine.setdefault(machine, []).append(pn)

    lines = [
        GENERATED_HEADER.format(source="the ipks in ipks/"),
        "#\n",
        "# Per-machine FPGA packages, from the ipks present at generation time.\n",
    ]
    for machine in sorted(by_machine):
        names = " ".join(sorted(by_machine[machine]))
        lines.append(f'\nRDEPENDS:${{PN}}:append:{machine} = " {names}"\n')

    fragment = GENERATED_DIR / "packagegroup-panda-fpga-apps.inc"
    fragment.write_text("".join(lines))
    print(f"Wrote {fragment.relative_to(REPO_DIR)}")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--release",
        metavar="TAG",
        help=f"PandABlocks-FPGA release tag (default: contents of {RELEASE_FILE.name})",
    )
    parser.add_argument(
        "--no-download",
        action="store_true",
        help="generate from the ipks already in ipks/ instead of fetching a release",
    )
    args = parser.parse_args()

    IPK_DIR.mkdir(exist_ok=True)

    if args.no_download:
        if args.release:
            parser.error("--release makes no sense with --no-download")
        print(f"Generating from the ipks already in {IPK_DIR.relative_to(REPO_DIR)}")
    else:
        tag = args.release or read_pinned_release()
        print(f"PandABlocks-FPGA release: {tag}")
        extract_tarball(download_tarball(tag))

    packages, boots, boot_version = collect_ipks()
    if not packages and not boots:
        die(f"no usable ipks in {IPK_DIR.relative_to(REPO_DIR)}")
    if not any(pn == SLOWFPGA_PN for pn, _pv, _filename in packages):
        warn(
            f"no {SLOWFPGA_PN} ipk in this release; pandabox images will have "
            "no slow FPGA firmware"
        )
    if not boots:
        warn(
            "no panda-fpga-boot ipk found; the build will fail to resolve "
            "PREFERRED_PROVIDER_virtual/fsbl"
        )

    # Regenerated from scratch every run, so a previous release's recipe can
    # never linger at a different PV alongside the current one.
    if GENERATED_DIR.exists():
        shutil.rmtree(GENERATED_DIR)
    GENERATED_DIR.mkdir(parents=True)

    write_package_recipes(packages)
    if boots:
        write_boot_recipe(boots, boot_version)
    write_packagegroup(packages)


if __name__ == "__main__":
    main()
