#!/usr/bin/env python3
"""Resolve the pinned PandABlocks-server release and generate its version .inc.

Companion to fetch-fpga-ipks.py, and part of the same step 1 of the build.

`panda-server_git.bb` and `kernel-module-panda_git.bb` build the server and its
driver out of one PandABlocks-server checkout, so they have to agree on which
commit that is.  The commit is pinned as a git tag in
`panda-server-release.txt`, and this script turns that tag into the `PV` and
`SRCREV` both recipes require:

    recipes-panda/panda-server-generated/panda-server-release.inc

which is gitignored, like the generated FPGA recipes.  Bumping the server is
then a one-line edit to `panda-server-release.txt`, with no sha to copy by hand
and no second recipe to keep in step.

The tag is resolved with `git ls-remote`, so this needs the network -- but only
when the tag actually changes: the generated .inc records the tag it came from
and a matching one is reused as is.  `--force` resolves again anyway.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent
RELEASE_FILE = REPO_DIR / "panda-server-release.txt"
GENERATED_DIR = REPO_DIR / "recipes-panda" / "panda-server-generated"
INC_FILE = GENERATED_DIR / "panda-server-release.inc"

# The repository both recipes fetch; their SRC_URI must point at this too.
SRC_REPO = "https://github.com/PandABlocks/PandABlocks-server"

# The tag of an already generated .inc, read back out of the PV it wrote.
PV_RE = re.compile(r'^PV = "(?P<tag>.+)\+git\$\{SRCPV\}"$', re.MULTILINE)
SRCREV_RE = re.compile(r'^SRCREV = "(?P<rev>[0-9a-f]{40})"$', re.MULTILINE)


def die(message):
    sys.exit(f"error: {message}")


def read_pinned_release():
    if not RELEASE_FILE.exists():
        die(f"{RELEASE_FILE.name} not found; pass --release instead")
    tag = RELEASE_FILE.read_text().strip()
    if not tag:
        die(f"{RELEASE_FILE.name} is empty")
    if len(tag.split()) > 1:
        die(f"{RELEASE_FILE.name} should hold a single release tag, got {tag!r}")
    return tag


def already_resolved(tag):
    """The sha a previous run pinned for this tag, or None to go and look.

    Re-resolving on every build would put the network on the path of a build
    that sstate could otherwise do offline, and a tag does not move.
    """
    if not INC_FILE.exists():
        return None
    text = INC_FILE.read_text()
    pv, srcrev = PV_RE.search(text), SRCREV_RE.search(text)
    if not pv or not srcrev or pv.group("tag") != tag:
        return None
    return srcrev.group("rev")


def resolve_tag(tag):
    """The commit `tag` names in SRC_REPO.

    An annotated tag has both a `refs/tags/<tag>` line for the tag object and a
    peeled `refs/tags/<tag>^{}` line for the commit; it is the commit we want,
    since that is what BitBake checks out.
    """
    ref = f"refs/tags/{tag}"
    print(f"Resolving {ref} in {SRC_REPO}")
    try:
        result = subprocess.run(
            ["git", "ls-remote", SRC_REPO, ref, ref + "^{}"],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        die("git not found; it is needed to resolve the release tag")
    if result.returncode != 0:
        die(f"git ls-remote {SRC_REPO} failed: {result.stderr.strip()}")

    revs = {}
    for line in result.stdout.splitlines():
        rev, _, name = line.partition("\t")
        revs[name] = rev
    if not revs:
        die(
            f"{SRC_REPO} has no tag {tag!r}; check {RELEASE_FILE.name} "
            "(or the --release you passed)"
        )
    return revs.get(ref + "^{}") or revs[ref]


def write_inc(tag, rev):
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    INC_FILE.write_text(
        f"# Generated by {Path(__file__).name} from {RELEASE_FILE.name}.\n"
        f"# Do not edit -- regenerate with ./{Path(__file__).name}\n"
        "#\n"
        "# Shared by panda-server and kernel-module-panda: one checkout, one\n"
        "# version, so they cannot drift apart.\n"
        "\n"
        f'SRCREV = "{rev}"\n'
        f'PV = "{tag}+git${{SRCPV}}"\n'
    )
    print(f"Wrote {INC_FILE.relative_to(REPO_DIR)}")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--release",
        metavar="TAG",
        help=f"PandABlocks-server release tag (default: contents of {RELEASE_FILE.name})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="resolve the tag again even if the generated .inc already pins it",
    )
    args = parser.parse_args()

    tag = args.release or read_pinned_release()
    print(f"PandABlocks-server release: {tag}")

    rev = None if args.force else already_resolved(tag)
    if rev:
        print(f"{INC_FILE.relative_to(REPO_DIR)} already pins {tag} at {rev[:12]}")
        return
    rev = resolve_tag(tag)
    write_inc(tag, rev)


if __name__ == "__main__":
    main()
