#!/usr/bin/env bash
designsdir="/boot/state/designs"
optionsdir="/boot/state/options"
mkdir -p "$designsdir" "$optionsdir"
/usr/bin/panda-webcontrol \
    --admindir /usr/share/web-admin/templates \
    --configdir "$designsdir" \
    --optionsdir "$optionsdir" \
    --etcdir /opt/etc/www \
    --enable-nav
