#!/usr/bin/env bash
designsdir="/boot/state/designs"
optionsdir="/boot/state/options"
mkdir -p "$designsdir" "$optionsdir"
/usr/bin/panda-webcontrol.py \
    --admindir /usr/share/web-admin/templates \
    --configdir "$designsdir" \
    --templatedesigns /usr/share/webcontrol/template_designs \
    --templatedir /usr/share/web-admin/templates \
    --optionsdir "$optionsdir" \
    --etcdir /opt/etc/www
