# PandABox
SRC_URI:pandabox = "https://github.com/PandABlocks/meta-panda/releases/download/4.0alpha1/panda-fpga-boot@pandabox-4.0-35-g99cec34-dirty.ipk;name=pandabox-boot"
SRC_URI[pandabox-boot.sha256sum] = "d35e36deb6828f17182ddd21fcabc4639cbc3e4010331d2df7f8fd300f6634d6"
# PandABrick
SRC_URI:pandabrick = "https://github.com/PandABlocks/PandABlocks-FPGA/releases/download/4.1/panda-fpga-boot_pandabrick-4.1_all.ipk;name=pandabrick-boot"
SRC_URI[pandabrick-boot.sha256sum] = "fd58b0f056af4091665f05b520962f223432b631a6f3acf7cdb557b933a39ddc"
# XU5 SoC on a ST1 board
SRC_URI:xu5-st1 = "https://github.com/PandABlocks/meta-panda/releases/download/4.0alpha1/panda-fpga-boot@xu5-st1-4.0-35-g99cec34-dirty.ipk;name=xu5-st1-boot"
SRC_URI[xu5-st1-boot.sha256sum] = "864d4527daaaeb27bd1b5b9495f76afe171347daf725509581039f6c4c6af652"
# Zedboard
SRC_URI:zedboard = "https://github.com/PandABlocks/meta-panda/releases/download/4.0alpha1/panda-fpga-boot_zedboard-4.1b1-2-g16147d6-dirty_all.ipk;name=zedboard-boot"
SRC_URI[zedboard-boot.sha256sum] = "ddadc3ac919e1be545f8447f27f91a98af8893f165bd89b1686f2ef6037a8ee7"
