# PandABox
SRC_URI:pandabox = "https://github.com/PandABlocks/PandABlocks-FPGA/releases/download/4.1/panda-fpga-boot_pandabox-4.1_all.ipk;name=pandabox-boot"
SRC_URI[pandabox-boot.sha256sum] = "5f76e9cefaa939ab535aadd43938f1ada3c39cd96c748c42d3c0b87ddc410741"
# PandABox2
SRC_URI:pandabox2 = "https://github.com/PandABlocks/meta-panda/releases/download/4.0alpha1/panda-fpga-boot_pandabox2-4.1-2-g55067cc-dirty_all.ipk;name=pandabox2-boot"
SRC_URI[pandabox2-boot.sha256sum] = "89f164478465ba8146586e8c33e3441bc540ee677ea000d90dfc68be143209aa"
# PandABrick
SRC_URI:pandabrick = "https://github.com/PandABlocks/PandABlocks-FPGA/releases/download/4.1/panda-fpga-boot_pandabrick-4.1_all.ipk;name=pandabrick-boot"
SRC_URI[pandabrick-boot.sha256sum] = "fd58b0f056af4091665f05b520962f223432b631a6f3acf7cdb557b933a39ddc"
# XU5 SoC on a ST1 board
SRC_URI:xu5-st1 = "https://github.com/PandABlocks/PandABlocks-FPGA/releases/download/4.1/panda-fpga-boot_xu5-st1-4.1_all.ipk;name=xu5-st1-boot"
SRC_URI[xu5-st1-boot.sha256sum] = "6c00f8f8ea0aedfe06869d5e1c8fcf653539fd97669010513975721345d3a9d7"
# Zedboard
SRC_URI:zedboard = "https://github.com/PandABlocks/meta-panda/releases/download/4.0alpha1/panda-fpga-boot_zedboard-4.1b1-2-g16147d6-dirty_all.ipk;name=zedboard-boot"
SRC_URI[zedboard-boot.sha256sum] = "ddadc3ac919e1be545f8447f27f91a98af8893f165bd89b1686f2ef6037a8ee7"
