on:
  workflow_call:
    inputs:
      machine:
        required: true
        type: string
env:
  KAS_MACHINE: ${{ inputs.machine }}
jobs:
  make_boot:
    runs-on:
      group: iris_runners
    container:
      image: ghcr.io/siemens/kas/kas:4.7
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build and gather
        run: |
          kas build kas.yml
          mkdir boot
          cp -Lf build/tmp/deploy/images/${{ inputs.machine }}/fitImage-petalinux-initramfs-image-${{ inputs.machine }}-${{ inputs.machine }} boot/image.ub
          cp -f build/tmp/deploy/images/${{ inputs.machine }}/rootfs.squashfs boot/
          cp -f build/tmp/deploy/images/${{ inputs.machine }}/boot.bin boot/
          cp -f build/tmp/deploy/images/${{ inputs.machine }}/boot.scr boot/
          cp -f build/tmp/deploy/images/${{ inputs.machine }}/target-defs boot/
          cd boot
          tar cvzf ../boot-${{ inputs.machine }}-${{ github.ref_name }}.tar.gz *

      - name: Upload boot
        uses: actions/upload-artifact@v4
        with:
          name: boot
          path: ${{ github.workspace }}/boot-${{ inputs.machine }}-${{ github.ref_name }}.tar.gz
          if-no-files-found: error
